"use client";

import DashboardLayout from "@/components/DashboardLayout";
import { operators, tours } from "@/lib/travelData";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, CircleAlert, Mail, MoreHorizontal, Phone, Plus, Search } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { useLocation } from "wouter";

export default function Admin() {
  const [location, setLocation] = useLocation(); const [published, setPublished] = useState(() => new Set(tours.map((tour) => tour.id))); const section = location.split("/")[2] || "overview";
  const inquiries = trpc.travel.inquiries.all.useQuery(undefined, { retry: false });
  const toggle = (id: number) => setPublished((current) => { const next = new Set(current); next.has(id) ? next.delete(id) : next.add(id); return next; });
  const content = section === "tours" ? <TourManagement published={published} toggle={toggle} /> : section === "operators" ? <OperatorManagement /> : section === "inquiries" ? <InquiryManagement inquiries={inquiries.data ?? []} /> : <Overview setLocation={setLocation} inquiryCount={inquiries.data?.length ?? 0} />;
  return <DashboardLayout mode="admin">{content}</DashboardLayout>;
}
function Overview({ setLocation, inquiryCount }: { setLocation: (path: string) => void; inquiryCount: number }) { return <section><span className="eyebrow">King Solomon Tours and Travels operations</span><h1 className="mt-2 font-display text-5xl text-[#263e34]">Good morning, admin.</h1><p className="mt-3 text-sm text-[#6b6255]">A concise view of the marketplace surfaces that need your attention.</p><div className="mt-8 grid gap-4 md:grid-cols-3"><AdminMetric label="Published tours" value={tours.length} tone="green" /><AdminMetric label="Verified operators" value={operators.length} tone="gold" /><AdminMetric label="Open inquiries" value={inquiryCount} tone="sand" /></div><div className="surface mt-8 p-6"><div className="flex items-center justify-between"><div><h2 className="font-display text-3xl text-[#263e34]">Next actions</h2><p className="mt-1 text-sm text-[#6b6255]">Review tours, including Lake Victoria boat rides, and follow up with travelers.</p></div><CircleAlert className="size-5 text-[#a07136]" /></div><div className="mt-6 grid gap-3 md:grid-cols-3"><AdminAction label="Review tours" description="Check listing presentation and publication state." onClick={() => setLocation("/admin/tours")} /><AdminAction label="Verify partners" description="Inspect operator profile details and contact information." onClick={() => setLocation("/admin/operators")} /><AdminAction label="Manage inquiries" description="Track new traveler requests in one clear queue." onClick={() => setLocation("/admin/inquiries")} /></div></div></section>; }
function TourManagement({ published, toggle }: { published: Set<number>; toggle: (id: number) => void }) { return <section><div className="flex flex-wrap items-end justify-between gap-4"><div><span className="eyebrow">Marketplace management</span><h1 className="mt-2 font-display text-4xl text-[#263e34]">Tour listings</h1></div><button onClick={() => toast("Tour creation form is ready for the next backend workflow.")} className="flex items-center gap-2 rounded-full bg-[#315b49] px-5 py-2.5 text-sm font-bold text-white"><Plus className="size-4" />Add tour</button></div><div className="surface mt-7 overflow-hidden"><div className="flex items-center justify-between border-b border-[#e6dccb] p-4"><div className="flex items-center gap-2 rounded-xl bg-[#f5efe3] px-3 py-2 text-sm text-[#807667]"><Search className="size-4" />Search listings</div><button onClick={() => toast("Listing filters are ready for refinement.")} className="text-xs font-bold text-[#315b49]">Filter</button></div><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-[#f8f3e8] text-[10px] uppercase tracking-[.14em] text-[#8a806f]"><tr><th className="p-4">Tour</th><th className="p-4">Category</th><th className="p-4">Region</th><th className="p-4">Status</th><th className="p-4"></th></tr></thead><tbody>{tours.map((tour) => <tr key={tour.id} className="border-t border-[#eee5d6]"><td className="p-4"><div className="flex items-center gap-3"><img src={tour.image} alt="" className="size-10 rounded-lg object-cover" /><div><p className="font-bold text-[#263e34]">{tour.title}</p><p className="mt-0.5 text-xs text-[#8a806f]">{tour.operator}</p></div></div></td><td className="p-4 text-[#645b50]">{tour.category}</td><td className="p-4 text-[#645b50]">{tour.region}</td><td className="p-4"><button onClick={() => toggle(tour.id)} className={`rounded-full px-3 py-1 text-xs font-bold ${published.has(tour.id) ? "bg-[#e7efe5] text-[#315b49]" : "bg-[#f7e5dd] text-[#a1503d]"}`}>{published.has(tour.id) ? "Published" : "Draft"}</button></td><td className="p-4"><button onClick={() => toast("Listing actions can be configured here.")} aria-label="Tour actions"><MoreHorizontal className="size-4 text-[#746b60]" /></button></td></tr>)}</tbody></table></div></div></section>; }
function OperatorManagement() { return <section><div><span className="eyebrow">Partner directory</span><h1 className="mt-2 font-display text-4xl text-[#263e34]">Operators</h1></div><div className="mt-7 grid gap-4 md:grid-cols-2">{operators.map((operator) => <article key={operator.name} className="surface p-5"><div className="flex items-start justify-between"><span className="grid size-10 place-items-center rounded-xl bg-[#e7efe5] font-display text-lg text-[#315b49]">{operator.name.slice(0, 1)}</span><span className="flex items-center gap-1 text-xs font-bold text-[#315b49]"><CheckCircle2 className="size-3.5" />Verified</span></div><h2 className="mt-5 font-display text-3xl text-[#263e34]">{operator.name}</h2><p className="mt-2 text-sm text-[#665d51]">{operator.focus}</p><div className="mt-4 border-t border-[#e9dfcf] pt-4">{operator.email ? <p className="text-xs text-[#7f7568]">{operator.email}</p> : null}<p className="flex items-center gap-1 text-xs text-[#7f7568]"><Phone className="size-3" />{operator.phone}</p><p className="mt-1 text-xs text-[#7f7568]">{operator.packages} packages</p></div></article>)}</div></section>; }
function InquiryManagement({ inquiries }: { inquiries: Array<{ id: number; travelerName: string; travelerEmail: string; travelerCount: number; status: string; createdAt: Date }> }) { return <section><div className="flex flex-wrap items-end justify-between gap-4"><div><span className="eyebrow">Traveler conversations</span><h1 className="mt-2 font-display text-4xl text-[#263e34]">Booking inquiries</h1><p className="mt-2 text-sm text-[#6b6255]">New booking inquiries will appear here for coordinated follow-up.</p></div><button onClick={() => toast("Inquiry filters are ready for refinement.")} className="rounded-full border border-[#315b49] px-4 py-2 text-sm font-bold text-[#315b49]">Filter inquiries</button></div>{inquiries.length ? <div className="surface mt-8 overflow-hidden"><div className="divide-y divide-[#ede3d3]">{inquiries.map((inquiry) => <article key={inquiry.id} className="flex flex-wrap items-center justify-between gap-4 p-5"><div><p className="font-bold text-[#263e34]">{inquiry.travelerName}</p><p className="mt-1 text-xs text-[#6b6255]">{inquiry.travelerEmail} · {inquiry.travelerCount} travelers</p></div><div className="text-right"><span className="rounded-full bg-[#f6e9ce] px-3 py-1 text-xs font-bold text-[#a07136]">{inquiry.status}</span><p className="mt-2 text-xs text-[#7d7467]">{new Date(inquiry.createdAt).toLocaleDateString()}</p></div></article>)}</div></div> : <div className="surface mt-8 p-9 text-center"><span className="mx-auto grid size-12 place-items-center rounded-2xl bg-[#e7efe5] text-[#315b49]"><Mail className="size-5" /></span><h2 className="mt-5 font-display text-3xl text-[#263e34]">Your inbox is clear.</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-[#6b6255]">When travelers send an inquiry from a tour page, it will be available here for the appropriate next step.</p></div>}</section>; }
function AdminMetric({ label, value, tone }: { label: string; value: number; tone: "green" | "gold" | "sand" }) { const colors = { green: "bg-[#e7efe5] text-[#315b49]", gold: "bg-[#f6e9ce] text-[#a07136]", sand: "bg-[#f1e9de] text-[#6f6354]" }; return <div className="surface p-5"><span className={`inline-flex rounded-full px-2 py-1 text-[10px] font-bold uppercase tracking-[.12em] ${colors[tone]}`}>Current</span><p className="mt-4 font-display text-4xl text-[#263e34]">{value}</p><p className="mt-1 text-sm text-[#6b6255]">{label}</p></div>; }
function AdminAction({ label, description, onClick }: { label: string; description: string; onClick: () => void }) { return <button onClick={onClick} className="rounded-2xl bg-[#f6efe3] p-4 text-left transition hover:bg-[#ece1ce]"><p className="font-bold text-[#263e34]">{label}</p><p className="mt-1 text-xs leading-5 text-[#6b6255]">{description}</p></button>; }
