"use client";

import DashboardLayout from "@/components/DashboardLayout";
import TourCard from "@/components/TourCard";
import { tours } from "@/lib/travelData";
import { trpc } from "@/lib/trpc";
import { ArrowRight, Bookmark, CalendarDays, Heart, MapPin, Send } from "lucide-react";
import { toast } from "sonner";
import { useLocation } from "wouter";

export default function Dashboard() {
  const [location, setLocation] = useLocation(); const isSaved = location.includes("/saved"); const isItineraries = location.includes("/itineraries");
  const saved = trpc.travel.saved.list.useQuery(undefined, { retry: false }); const itineraries = trpc.travel.itineraries.list.useQuery(undefined, { retry: false }); const inquiries = trpc.travel.inquiries.mine.useQuery(undefined, { retry: false });
  const lakeVictoriaTours = tours.filter((tour) => tour.region === "Lake Victoria");
  const renderContent = () => {
    if (isSaved) return <section><span className="eyebrow">Your collection</span><h1 className="mt-2 font-display text-4xl text-[#263e34]">Saved tours</h1><p className="mt-2 text-sm text-[#6b6255]">Keep the experiences you’re considering close by.</p>{saved.isLoading ? <p className="mt-8 text-sm text-[#6b6255]">Loading saved tours…</p> : saved.data?.length ? <div className="mt-8 grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{saved.data.map((item) => tours.find((tour) => tour.id === item.saved.tourId)).filter((tour): tour is (typeof tours)[number] => Boolean(tour)).map((tour) => <TourCard key={tour.id} tour={tour} />)}</div> : <Empty icon={Heart} title="Nothing saved yet" detail="When you find a journey that feels right, use the heart icon to keep it here." action="Explore tours" onClick={() => setLocation("/tours")} />}</section>;
    if (isItineraries) return <section><span className="eyebrow">Your ideas, organised</span><h1 className="mt-2 font-display text-4xl text-[#263e34]">My itineraries</h1><p className="mt-2 text-sm text-[#6b6255]">Plans you create with King Solomon Tours and Travels can become an easy reference here.</p>{itineraries.isLoading ? <p className="mt-8 text-sm text-[#6b6255]">Loading itineraries…</p> : itineraries.data?.length ? <div className="mt-8 space-y-3">{itineraries.data.map((itinerary) => <div key={itinerary.id} className="surface flex items-center justify-between p-5"><div><p className="font-bold text-[#263e34]">{itinerary.title}</p><p className="mt-1 text-xs text-[#6b6255]">Last updated {new Date(itinerary.updatedAt).toLocaleDateString()}</p></div><ArrowRight className="size-4 text-[#315b49]" /></div>)}</div> : <Empty icon={CalendarDays} title="Start an itinerary" detail="Describe your ideal Kenya trip, and King Solomon Tours and Travels will help you shape the first version." action="Plan My Trip" onClick={() => setLocation("/planner")} />}</section>;
    return <section><span className="eyebrow">Welcome back</span><h1 className="mt-2 font-display text-5xl text-[#263e34]">Your Kenya, taking shape.</h1><p className="mt-3 max-w-xl text-sm leading-6 text-[#6b6255]">From trips you’ve tucked away to operators you’ve contacted, this is where your travel ideas stay together.</p><div className="mt-8 grid gap-4 sm:grid-cols-3"><Metric icon={Bookmark} label="Saved tours" value={saved.data?.length ?? 0} action={() => setLocation("/dashboard/saved")} /><Metric icon={Send} label="Booking inquiries" value={inquiries.data?.length ?? 0} action={() => toast("Your submitted booking inquiries are counted here.")} /><Metric icon={CalendarDays} label="Itineraries" value={itineraries.data?.length ?? 0} action={() => setLocation("/dashboard/itineraries")} /></div><div className="mt-10 grid gap-6 xl:grid-cols-[1.1fr_.9fr]"><div className="surface overflow-hidden p-6"><div className="flex items-center justify-between"><div><p className="font-display text-3xl text-[#263e34]">Lake Victoria boat rides</p><p className="mt-1 text-sm text-[#6b6255]">Three island days to consider next.</p></div><button onClick={() => setLocation("/tours")} className="text-sm font-bold text-[#315b49]">View all</button></div><div className="mt-6 grid gap-3">{lakeVictoriaTours.slice(0, 2).map((tour) => <button key={tour.id} onClick={() => setLocation(`/tours/${tour.slug}`)} className="flex items-center gap-4 rounded-2xl bg-[#f6efe3] p-3 text-left transition hover:bg-[#eee3d0]"><img src={tour.image} alt="" className="size-16 rounded-xl object-cover" /><div><p className="text-xs font-bold uppercase tracking-[.12em] text-[#a07136]">{tour.destination}</p><p className="mt-1 font-bold text-[#263e34]">{tour.title}</p></div><ArrowRight className="ml-auto size-4 text-[#315b49]" /></button>)}</div></div><div className="rounded-[1.5rem] bg-[#20382f] p-7 text-white"><MapPin className="size-6 text-[#f4cc7b]" /><p className="mt-6 font-display text-3xl">A trip is a collection of good choices.</p><p className="mt-3 text-sm leading-6 text-white/70">Begin with a feeling and let King Solomon Tours and Travels help you explore Kenya with more care.</p><button onClick={() => setLocation("/planner")} className="mt-7 rounded-full bg-[#d5a44f] px-5 py-2.5 text-sm font-bold text-[#20382f]">Plan My Trip</button></div></div></section>;
  };
  return <DashboardLayout>{renderContent()}</DashboardLayout>;
}
function Metric({ icon: Icon, label, value, action }: { icon: typeof Bookmark; label: string; value: number; action: () => void }) { return <button onClick={action} className="surface p-5 text-left transition hover:-translate-y-0.5"><Icon className="size-5 text-[#a07136]" /><p className="mt-5 font-display text-4xl text-[#263e34]">{value}</p><p className="mt-1 text-sm text-[#6b6255]">{label}</p></button>; }
function Empty({ icon: Icon, title, detail, action, onClick }: { icon: typeof Bookmark; title: string; detail: string; action: string; onClick: () => void }) { return <div className="surface mt-8 max-w-xl p-8"><span className="grid size-12 place-items-center rounded-2xl bg-[#e7efe5] text-[#315b49]"><Icon className="size-5" /></span><h2 className="mt-5 font-display text-3xl text-[#263e34]">{title}</h2><p className="mt-2 text-sm leading-6 text-[#6b6255]">{detail}</p><button onClick={onClick} className="mt-6 rounded-full bg-[#315b49] px-5 py-2.5 text-sm font-bold text-white">{action}</button></div>; }
