"use client";

import { useEffect, useState } from "react";
import { travelImages } from "@/lib/travelData";

export default function ClientRoute({ children, variant = "standard" }: { children: React.ReactNode; variant?: "home" | "standard" }) {
  const [mounted, setMounted] = useState(false);
  useEffect(() => setMounted(true), []);
  const fallback = variant === "home" ? <main className="relative min-h-[680px] overflow-hidden bg-[#17352c] pt-[76px] text-white" aria-busy="true"><img src={travelImages.mara} alt="Kenya savannah at golden hour" className="absolute inset-0 h-full w-full object-cover opacity-70" /><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(16,46,37,.93)_0%,rgba(16,46,37,.7)_42%,rgba(17,37,30,.28)_100%)]" /><div className="container relative flex min-h-[604px] items-end pb-12 pt-24 md:pb-20 md:pt-28"><div className="max-w-3xl"><p className="mb-5 text-[11px] font-bold uppercase tracking-[.22em] text-[#f4cc7b]">Kenya, your way</p><h1 className="font-display text-5xl leading-[.96] tracking-tight sm:text-6xl md:text-8xl">Leave room for<br /><em className="text-[#f4cc7b]">wonder.</em></h1><p className="mt-6 max-w-xl text-base leading-7 text-white/80 md:text-lg">Discover Kenya’s unforgettable places, thoughtful guides, and stays selected around your rhythm.</p></div></div></main> : <main className="min-h-screen bg-[#f8f3e8] px-6 py-10 text-[#263e34]" aria-busy="true"><div className="mx-auto grid max-w-6xl gap-8 lg:grid-cols-[1.1fr_.9fr] lg:items-center"><div><p className="text-[11px] font-bold uppercase tracking-[.2em] text-[#a07136]">King Solomon Tours and Travels</p><h1 className="mt-4 font-display text-5xl leading-tight">Kenya tours, safaris, and curated experiences.</h1><p className="mt-5 max-w-2xl text-base leading-7 text-[#665d51]">Discover memorable journeys across Kenya, with package options selected around your pace and interests.</p><nav className="mt-8 flex flex-wrap gap-3 text-sm font-bold text-[#315b49]"><a href="/tours">Explore Kenya tours</a><a href="/operators">Meet operators</a><a href="/planner">Plan My Trip</a></nav></div><div className="grid grid-cols-2 gap-3"><img src={travelImages.mara} alt="Maasai Mara safari landscape" className="col-span-2 h-72 w-full rounded-[1.5rem] object-cover" /><img src={travelImages.takawiri} alt="Takawiri Island tour package" className="h-36 w-full rounded-2xl object-cover" /><img src={travelImages.mfangano} alt="Mfangano Island tour package" className="h-36 w-full rounded-2xl object-cover" /></div></div></main>;
  return <div suppressHydrationWarning>{mounted ? children : fallback}</div>;
}
