import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { Sidebar, SidebarContent, SidebarFooter, SidebarHeader, SidebarInset, SidebarMenu, SidebarMenuButton, SidebarMenuItem, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { BarChart3, Bookmark, Building2, CalendarDays, Compass, LayoutDashboard, LogOut, Mail, PanelLeft } from "lucide-react";
import { useLocation } from "wouter";

const travelerItems = [{ icon: LayoutDashboard, label: "Overview", path: "/dashboard" }, { icon: Bookmark, label: "Saved tours", path: "/dashboard/saved" }, { icon: CalendarDays, label: "My itineraries", path: "/dashboard/itineraries" }];
const adminItems = [{ icon: BarChart3, label: "Overview", path: "/admin" }, { icon: Compass, label: "Tour listings", path: "/admin/tours" }, { icon: Building2, label: "Operators", path: "/admin/operators" }, { icon: Mail, label: "Inquiries", path: "/admin/inquiries" }];

export default function DashboardLayout({ children, mode = "traveler" }: { children: React.ReactNode; mode?: "traveler" | "admin" }) {
  const { loading, user, logout } = useAuth();
  const [location, setLocation] = useLocation();
  const items = mode === "admin" ? adminItems : travelerItems;
  if (loading) return <div className="grid min-h-screen place-items-center bg-[#f8f3e8]"><div className="size-9 animate-pulse rounded-full bg-[#d5a44f]" /></div>;
  if (!user) return <div className="grid min-h-screen place-items-center bg-[#f8f3e8] px-5"><div className="surface max-w-md p-8 text-center"><span className="eyebrow">Tulia Trails account</span><h1 className="mt-3 font-display text-4xl text-[#263e34]">Your travel space awaits.</h1><p className="mt-3 text-sm leading-6 text-[#6b6255]">Sign in to collect your saved tours, booking enquiries, and trip ideas in one considered place.</p><Button onClick={startLogin} className="mt-7 w-full rounded-full bg-[#315b49] text-white hover:bg-[#254939]">Sign in</Button></div></div>;
  if (mode === "admin" && user.role !== "admin") return <div className="grid min-h-screen place-items-center bg-[#f8f3e8] px-5"><div className="surface max-w-md p-8 text-center"><span className="eyebrow">Restricted area</span><h1 className="mt-3 font-display text-4xl text-[#263e34]">Admin access required.</h1><p className="mt-3 text-sm leading-6 text-[#6b6255]">This workspace is reserved for Tulia Trails administrators.</p><Button onClick={() => setLocation("/")} className="mt-7 rounded-full bg-[#315b49] text-white hover:bg-[#254939]">Return home</Button></div></div>;
  return <SidebarProvider><Sidebar className="border-r-0 bg-[#20382f] text-white"><SidebarHeader className="h-20 justify-center px-4"><button onClick={() => setLocation("/")} className="flex items-center gap-2 text-left"><span className="grid size-8 place-items-center rounded-full border border-white/30 text-sm">T</span><span className="font-display text-xl">Tulia Trails</span></button></SidebarHeader><SidebarContent className="px-3"><p className="px-3 pb-3 text-[10px] font-bold uppercase tracking-[.18em] text-white/40">{mode === "admin" ? "Operations" : "My travel"}</p><SidebarMenu>{items.map((item) => <SidebarMenuItem key={item.path}><SidebarMenuButton isActive={location === item.path} onClick={() => setLocation(item.path)} tooltip={item.label} className="h-11 rounded-xl text-white/80 hover:bg-white/10 hover:text-white data-[active=true]:bg-[#d5a44f] data-[active=true]:text-[#20382f]"><item.icon className="size-4" /><span>{item.label}</span></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarContent><SidebarFooter className="p-4"><div className="mb-3 flex items-center gap-3 rounded-xl bg-white/8 p-2"><Avatar className="size-8"><AvatarFallback className="bg-[#d5a44f] text-xs text-[#20382f]">{user.name?.slice(0, 1).toUpperCase() || "T"}</AvatarFallback></Avatar><div className="min-w-0"><p className="truncate text-xs font-bold">{user.name || "Traveler"}</p><p className="truncate text-[10px] text-white/50">{user.email || "Account"}</p></div></div><button onClick={logout} className="flex w-full items-center gap-2 rounded-lg px-2 py-2 text-xs font-semibold text-white/60 transition hover:bg-white/10 hover:text-white"><LogOut className="size-3.5" /> Sign out</button></SidebarFooter></Sidebar><SidebarInset className="bg-[#f8f3e8]"><div className="sticky top-0 z-20 flex h-16 items-center gap-3 border-b border-[#e7dcc8] bg-[#fffdf8]/90 px-4 backdrop-blur"><SidebarTrigger className="md:hidden" /><button onClick={() => setLocation("/")} className="ml-auto text-xs font-bold text-[#315b49]">Back to explore</button></div><main className="min-h-[calc(100vh-4rem)] p-5 md:p-9">{children}</main></SidebarInset></SidebarProvider>;
}
